name: Build Samples Test MonoGame.Helper

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #- uses: actions/checkout@master

    #- name: Setup MSBuild.exe
    #  uses: warrenbuckley/Setup-MSBuild@v1
    - uses: actions/checkout@master

    - name: Setup VS2019
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build Collision Sample
      working-directory: samples/Collision
      run: msbuild Collision.csproj
    
    - name: Build SceneGraph Sample
      working-directory: samples/SceneGraph
      run: msbuild SceneGraph.csproj
    
    - name: Build SpriteAnimation Sample
      working-directory: samples/SpriteAnimation
      run: msbuild SpriteAnimation.csproj
