name: Create Release MonoGame.Helper

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout under $GITHUB_WORKSPACE
      id: checkout
      uses: actions/checkout@v2
    
    - name: Compress DLL # This would actually build your project, using zip for an example artifact
      run: |
        echo '${{ github.workspace }}/../dist/MonoGame.Helper.dll'
        zip --junk-paths MonoGame.Helper ${{ github.workspace }}/../dist/MonoGame.Helper.dll
        zip --junk-paths MonoGame.Helper.Physic ${{ github.workspace }}/../dist/MonoGame.Helper.Physic.dll
          
    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1.1.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload a Release Asset - MonoGame.Helper
      id: upload-release-asset-mh
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{ github.workspace }}/../dist/MonoGame.Helper.zip
        asset_name: MonoGame.Helper.zip
        asset_content_type: application/zip  
        
    - name: Upload a Release Asset - MonoGame.Helper.Physic
      id: upload-release-asset-mhp 
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{ github.workspace }}/../dist/MonoGame.Helper.Physic.zip
        asset_name: MonoGame.Helper.Physic.zip
        asset_content_type: application/zip
