name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore src/Curupira2D-NoSamples.sln
      
    - name: Build
      run: dotnet build --no-restore src/Curupira2D-NoSamples.sln

    # - name: Publish NuGet - Curupira2D
    #   uses: brandedoutcast/publish-nuget@v2.5.5
    #   with:
    #     # Filepath of the project to be packaged, relative to root of repository
    #     PROJECT_FILE_PATH: src/Curupira2D/Curupira2D.csproj
    #     # API key to authenticate with NuGet server
    #     NUGET_KEY: ${{secrets.CURUPIRA2D_TOKEN}}
        
    # - name: Publish NuGet - Curupira2D.GameComponents
    #   uses: brandedoutcast/publish-nuget@v2.5.5
    #   with:
    #     # Filepath of the project to be packaged, relative to root of repository
    #     PROJECT_FILE_PATH: src/Curupira2D.GameComponents/Curupira2D.GameComponents.csproj
    #     # API key to authenticate with NuGet server
    #     NUGET_KEY: ${{secrets.CURUPIRA2D_TOKEN}} 
      
    - name: Publish NuGet - Curupira2D
      uses: rollycodes/publish-nuget-private@v3.0.1
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/Curupira2D/Curupira2D.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.CURUPIRA2D_TOKEN}}
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://api.nuget.org/v3/index.json

    - name: Publish NuGet - Curupira2D.GameComponents
      uses: rollycodes/publish-nuget-private@v3.0.1
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/Curupira2D.GameComponents/Curupira2D.GameComponents.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.CURUPIRA2D_TOKEN}}
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://api.nuget.org/v3/index.json
