name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/<organization>/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.CURUPIRA2D_TOKEN}}
        
    - name: Restore dependencies
      run: dotnet restore src/Curupira2D.sln
      
    - name: Build
      run: dotnet build --no-restore src/Curupira2D.sln

    - name: Generate NuGet package
      run: dotnet pack src/Curupira2D.sln -c Release -o nupkgs  

    - name: Push generated package to GitHub registry
      run: dotnet nuget push nupkgs/*.nupkg --skip-duplicate --no-symbols true
